export interface ThemeColors {
  primary: string;
  primaryDark: string;
  primaryLight: string;
  accent: string;
  accentDark: string;
  accentLight: string;
  bg: string;
  bgAlt: string;
  surface: string;
  surfaceAlt: string;
  textPrimary: string;
  textSecondary: string;
  textInverse: string;
  border: string;
  success: string;
  error: string;
  warning: string;
  info: string;
}

export interface ThemePreset {
  id: string;
  nameRu: string;
  nameUk: string;
  nameEn: string;
  colors: ThemeColors;
}

export const THEMES: ThemePreset[] = [
  {
    id: 'default',
    nameRu: 'Синяя (по умолчанию)',
    nameUk: 'Синя (за замовчуванням)',
    nameEn: 'Blue (Default)',
    colors: {
      primary: '#3b82f6',
      primaryDark: '#2563eb',
      primaryLight: '#60a5fa',
      accent: '#8b5cf6',
      accentDark: '#7c3aed',
      accentLight: '#a78bfa',
      bg: '#f8fafc',
      bgAlt: '#f1f5f9',
      surface: '#ffffff',
      surfaceAlt: '#f1f5f9',
      textPrimary: '#0f172a',
      textSecondary: '#64748b',
      textInverse: '#f8fafc',
      border: '#e2e8f0',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#3b82f6',
    },
  },
  {
    id: 'emerald',
    nameRu: 'Изумрудная',
    nameUk: 'Смарагдова',
    nameEn: 'Emerald',
    colors: {
      primary: '#10b981',
      primaryDark: '#059669',
      primaryLight: '#34d399',
      accent: '#14b8a6',
      accentDark: '#0d9488',
      accentLight: '#5eead4',
      bg: '#f0fdf4',
      bgAlt: '#ecfdf5',
      surface: '#ffffff',
      surfaceAlt: '#ecfdf5',
      textPrimary: '#022c22',
      textSecondary: '#4b5563',
      textInverse: '#f0fdf4',
      border: '#d1fae5',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#06b6d4',
    },
  },
  {
    id: 'sunset',
    nameRu: 'Закат',
    nameUk: 'Захід сонця',
    nameEn: 'Sunset',
    colors: {
      primary: '#f97316',
      primaryDark: '#ea580c',
      primaryLight: '#fb923c',
      accent: '#e11d48',
      accentDark: '#be123c',
      accentLight: '#fb7185',
      bg: '#fffbeb',
      bgAlt: '#fef3c7',
      surface: '#ffffff',
      surfaceAlt: '#fef3c7',
      textPrimary: '#1c1917',
      textSecondary: '#78716c',
      textInverse: '#fffbeb',
      border: '#fed7aa',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#f97316',
    },
  },
  {
    id: 'midnight',
    nameRu: 'Полночь',
    nameUk: 'Опівніч',
    nameEn: 'Midnight',
    colors: {
      primary: '#6366f1',
      primaryDark: '#4f46e5',
      primaryLight: '#818cf8',
      accent: '#a855f7',
      accentDark: '#9333ea',
      accentLight: '#c084fc',
      bg: '#0f172a',
      bgAlt: '#1e293b',
      surface: '#1e293b',
      surfaceAlt: '#334155',
      textPrimary: '#f1f5f9',
      textSecondary: '#94a3b8',
      textInverse: '#0f172a',
      border: '#334155',
      success: '#34d399',
      error: '#f87171',
      warning: '#fbbf24',
      info: '#818cf8',
    },
  },
  {
    id: 'rose',
    nameRu: 'Розовая',
    nameUk: 'Рожева',
    nameEn: 'Rose',
    colors: {
      primary: '#e11d48',
      primaryDark: '#be123c',
      primaryLight: '#fb7185',
      accent: '#a855f7',
      accentDark: '#9333ea',
      accentLight: '#c084fc',
      bg: '#fff1f2',
      bgAlt: '#ffe4e6',
      surface: '#ffffff',
      surfaceAlt: '#ffe4e6',
      textPrimary: '#1c1917',
      textSecondary: '#6b7280',
      textInverse: '#fff1f2',
      border: '#fecdd3',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#e11d48',
    },
  },
  {
    id: 'ocean',
    nameRu: 'Океан',
    nameUk: 'Океан',
    nameEn: 'Ocean',
    colors: {
      primary: '#0891b2',
      primaryDark: '#0e7490',
      primaryLight: '#22d3ee',
      accent: '#6366f1',
      accentDark: '#4f46e5',
      accentLight: '#818cf8',
      bg: '#ecfeff',
      bgAlt: '#cffafe',
      surface: '#ffffff',
      surfaceAlt: '#cffafe',
      textPrimary: '#0c4a6e',
      textSecondary: '#64748b',
      textInverse: '#ecfeff',
      border: '#a5f3fc',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#0891b2',
    },
  },
  {
    id: 'lavender',
    nameRu: 'Лавандовая',
    nameUk: 'Лавандова',
    nameEn: 'Lavender',
    colors: {
      primary: '#7c3aed',
      primaryDark: '#6d28d9',
      primaryLight: '#a78bfa',
      accent: '#ec4899',
      accentDark: '#db2777',
      accentLight: '#f472b6',
      bg: '#faf5ff',
      bgAlt: '#f3e8ff',
      surface: '#ffffff',
      surfaceAlt: '#f3e8ff',
      textPrimary: '#1e1b4b',
      textSecondary: '#6b7280',
      textInverse: '#faf5ff',
      border: '#e9d5ff',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#7c3aed',
    },
  },
  {
    id: 'amber',
    nameRu: 'Янтарная',
    nameUk: 'Бурштинова',
    nameEn: 'Amber',
    colors: {
      primary: '#d97706',
      primaryDark: '#b45309',
      primaryLight: '#fbbf24',
      accent: '#059669',
      accentDark: '#047857',
      accentLight: '#34d399',
      bg: '#fffbeb',
      bgAlt: '#fef3c7',
      surface: '#ffffff',
      surfaceAlt: '#fef3c7',
      textPrimary: '#1c1917',
      textSecondary: '#78716c',
      textInverse: '#fffbeb',
      border: '#fde68a',
      success: '#10b981',
      error: '#ef4444',
      warning: '#d97706',
      info: '#0891b2',
    },
  },
  {
    id: 'slate',
    nameRu: 'Графитовая',
    nameUk: 'Графітова',
    nameEn: 'Slate',
    colors: {
      primary: '#475569',
      primaryDark: '#334155',
      primaryLight: '#94a3b8',
      accent: '#0ea5e9',
      accentDark: '#0284c7',
      accentLight: '#38bdf8',
      bg: '#f8fafc',
      bgAlt: '#f1f5f9',
      surface: '#ffffff',
      surfaceAlt: '#f1f5f9',
      textPrimary: '#0f172a',
      textSecondary: '#64748b',
      textInverse: '#f8fafc',
      border: '#cbd5e1',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#0ea5e9',
    },
  },
  {
    id: 'forest',
    nameRu: 'Лесная',
    nameUk: 'Лісова',
    nameEn: 'Forest',
    colors: {
      primary: '#15803d',
      primaryDark: '#166534',
      primaryLight: '#4ade80',
      accent: '#a16207',
      accentDark: '#854d0e',
      accentLight: '#facc15',
      bg: '#f0fdf4',
      bgAlt: '#dcfce7',
      surface: '#ffffff',
      surfaceAlt: '#dcfce7',
      textPrimary: '#14532d',
      textSecondary: '#4b5563',
      textInverse: '#f0fdf4',
      border: '#bbf7d0',
      success: '#15803d',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#0891b2',
    },
  },
  {
    id: 'noir',
    nameRu: 'Нуар',
    nameUk: 'Нуар',
    nameEn: 'Noir',
    colors: {
      primary: '#e2e8f0',
      primaryDark: '#cbd5e1',
      primaryLight: '#f1f5f9',
      accent: '#f59e0b',
      accentDark: '#d97706',
      accentLight: '#fbbf24',
      bg: '#09090b',
      bgAlt: '#18181b',
      surface: '#18181b',
      surfaceAlt: '#27272a',
      textPrimary: '#fafafa',
      textSecondary: '#a1a1aa',
      textInverse: '#09090b',
      border: '#27272a',
      success: '#34d399',
      error: '#f87171',
      warning: '#fbbf24',
      info: '#e2e8f0',
    },
  },
  {
    id: 'coral',
    nameRu: 'Коралловая',
    nameUk: 'Коралова',
    nameEn: 'Coral',
    colors: {
      primary: '#f43f5e',
      primaryDark: '#e11d48',
      primaryLight: '#fb7185',
      accent: '#06b6d4',
      accentDark: '#0891b2',
      accentLight: '#22d3ee',
      bg: '#fff1f2',
      bgAlt: '#ffe4e6',
      surface: '#ffffff',
      surfaceAlt: '#ffe4e6',
      textPrimary: '#1c1917',
      textSecondary: '#78716c',
      textInverse: '#fff1f2',
      border: '#fecdd3',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#06b6d4',
    },
  },
  {
    id: 'northern',
    nameRu: 'Северное сияние',
    nameUk: 'Північне сяйво',
    nameEn: 'Northern Lights',
    colors: {
      primary: '#2dd4bf',
      primaryDark: '#14b8a6',
      primaryLight: '#5eead4',
      accent: '#c084fc',
      accentDark: '#a855f7',
      accentLight: '#d8b4fe',
      bg: '#042f2e',
      bgAlt: '#134e4a',
      surface: '#134e4a',
      surfaceAlt: '#115e59',
      textPrimary: '#f0fdfa',
      textSecondary: '#99f6e4',
      textInverse: '#042f2e',
      border: '#115e59',
      success: '#2dd4bf',
      error: '#fb7185',
      warning: '#fbbf24',
      info: '#5eead4',
    },
  },
  {
    id: 'copper',
    nameRu: 'Медная',
    nameUk: 'Мідна',
    nameEn: 'Copper',
    colors: {
      primary: '#c2410c',
      primaryDark: '#9a3412',
      primaryLight: '#fb923c',
      accent: '#4f46e5',
      accentDark: '#4338ca',
      accentLight: '#818cf8',
      bg: '#fdf8f6',
      bgAlt: '#f5ebe6',
      surface: '#ffffff',
      surfaceAlt: '#f5ebe6',
      textPrimary: '#1c1917',
      textSecondary: '#78716c',
      textInverse: '#fdf8f6',
      border: '#e7d5cc',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#c2410c',
    },
  },
  {
    id: 'arctic',
    nameRu: 'Арктика',
    nameUk: 'Арктика',
    nameEn: 'Arctic',
    colors: {
      primary: '#0284c7',
      primaryDark: '#0369a1',
      primaryLight: '#38bdf8',
      accent: '#8b5cf6',
      accentDark: '#7c3aed',
      accentLight: '#a78bfa',
      bg: '#f0f9ff',
      bgAlt: '#e0f2fe',
      surface: '#ffffff',
      surfaceAlt: '#e0f2fe',
      textPrimary: '#0c4a6e',
      textSecondary: '#64748b',
      textInverse: '#f0f9ff',
      border: '#bae6fd',
      success: '#10b981',
      error: '#ef4444',
      warning: '#f59e0b',
      info: '#0284c7',
    },
  },
];

const CSS_VAR_MAP: Record<keyof ThemeColors, string> = {
  primary: '--color-primary',
  primaryDark: '--color-primary-dark',
  primaryLight: '--color-primary-light',
  accent: '--color-accent',
  accentDark: '--color-accent-dark',
  accentLight: '--color-accent-light',
  bg: '--color-bg',
  bgAlt: '--color-bg-alt',
  surface: '--color-surface',
  surfaceAlt: '--color-surface-alt',
  textPrimary: '--color-text-primary',
  textSecondary: '--color-text-secondary',
  textInverse: '--color-text-inverse',
  border: '--color-border',
  success: '--color-success',
  error: '--color-error',
  warning: '--color-warning',
  info: '--color-info',
};

export function applyTheme(themeId: string) {
  const theme = THEMES.find((t) => t.id === themeId);
  if (!theme) return;

  const root = document.documentElement;
  for (const [key, cssVar] of Object.entries(CSS_VAR_MAP)) {
    root.style.setProperty(cssVar, theme.colors[key as keyof ThemeColors]);
  }

  const r = parseInt(theme.colors.primary.slice(1, 3), 16);
  const g = parseInt(theme.colors.primary.slice(3, 5), 16);
  const b = parseInt(theme.colors.primary.slice(5, 7), 16);
  root.style.setProperty('--shadow-focus', `0 0 0 3px rgba(${r}, ${g}, ${b}, 0.35)`);
}

export function resetTheme() {
  const root = document.documentElement;
  for (const cssVar of Object.values(CSS_VAR_MAP)) {
    root.style.removeProperty(cssVar);
  }
  root.style.removeProperty('--shadow-focus');
}
